const LOCK_THRESHOLD_PX=15,MAX_PULL_DISTANCE=120,TAP_SLOP_PX=8;
export function initSlingshot(el,cbs={}){const{onArm,onLock,onPull,onRelease,onCancel,onTap}=cbs;
let ph='idle',pId=null,sX=0,sY=0,lDir=null,lPV={x:0,y:0},lPN=0,aD=0;
function clamp(v,lo,hi){return Math.max(lo,Math.min(hi,v))}function dist(dx,dy){return Math.sqrt(dx*dx+dy*dy)}
function addWL(){window.addEventListener('pointermove',hPM);window.addEventListener('pointerup',hPU);window.addEventListener('pointercancel',hPC)}function removeWL(){window.removeEventListener('pointermove',hPM);window.removeEventListener('pointerup',hPU);window.removeEventListener('pointercancel',hPC)}
function hPD(e){if(ph!=='idle')return;if(e.pointerType==='mouse'&&e.button!==0)return;const tEl=e.target;if(tEl instanceof Element&&tEl.closest('button, a, input, textarea, select, [data-spa-no-sling="true"]')){return}if(e.cancelable)e.preventDefault();ph='armed';pId=e.pointerId;sX=e.clientX;sY=e.clientY;lPV={x:0,y:0};lPN=0;lDir=null;aD=0;try{el.setPointerCapture(e.pointerId)}catch(_e){}el.style.touchAction='none';addWL();if(typeof onArm==='function')onArm()}
function hPM(e){if(e.pointerId!==pId)return;if(ph!=='armed'&&ph!=='locked')return;const dx=e.clientX-sX;const dy=e.clientY-sY;const d=dist(dx,dy);aD=d;if(ph==='armed'){if(d<LOCK_THRESHOLD_PX)return;const adx=Math.abs(dx);const ady=Math.abs(dy);lDir=adx>=ady?(dx<0?'next':'prev'):(dy<0?'next':'prev');lPV={x:dx,y:dy};lPN=clamp(d/MAX_PULL_DISTANCE,0,1);ph='locked';let lA=true;if(typeof onLock==='function'){try{lA=onLock({direction:lDir,pullVector:lPV,pullNormalized:lPN})!==false}catch(_err){lA=false}}if(!lA){ph='idle';pId=null;lDir=null;removeWL();el.style.touchAction='';try{if(e.pointerId!=null)el.releasePointerCapture(e.pointerId)}catch(_err){}return}return}lPV={x:dx,y:dy};lPN=clamp(d/MAX_PULL_DISTANCE,0,1);if(typeof onPull==='function'){try{onPull({pullVector:lPV,pullNormalized:lPN})}catch(_err){fin(e,true)}}}
function fin(e,isCan){if(e&&e.pointerId!==pId)return;if(ph==='idle')return;removeWL();el.style.touchAction='';const wL=ph==='locked';const sAD=aD;const sDir=lDir;const sPV={...lPV};const sPN=lPN;ph='idle';pId=null;lDir=null;aD=0;if(isCan||!wL){if(isCan){if(typeof onCancel==='function'){try{onCancel()}catch(_err){}}}else{if(sAD<=TAP_SLOP_PX&&typeof onTap==='function'){try{onTap()}catch(_err){}}}return}if(typeof onRelease==='function'){try{onRelease({direction:sDir,pullVector:sPV,pullNormalized:sPN})}catch(_err){if(typeof onCancel==='function'){try{onCancel()}catch(_err2){}}}}}
function hPU(e){fin(e,false)}function hPC(e){fin(e,true)}
el.addEventListener('pointerdown',hPD);
return{destroy(){el.removeEventListener('pointerdown',hPD);if(ph!=='idle')fin(null,true);removeWL();el.style.touchAction='';ph='idle';pId=null}}}
